const products = [
  {
    name: "Apple Watch Series 8",
    price: 399.00,
    originalPrice: 499.00,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop",
    description: "Advanced health sensors and apps, track your daily activity, heart rate, and workouts with crystal clear always-on Retina display.",
    category: "electronics",
    stock: 45,
    rating: 4.8,
    reviews: 320,
    brand: "Apple",
    featured: true
  },
  {
    name: "Sony WH-1000XM5 Wireless Headphones",
    price: 348.00,
    originalPrice: 399.99,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop",
    description: "Industry-leading noise cancellation with two processors and 8 microphones. Magnificent sound engineered to perfection.",
    category: "electronics",
    stock: 30,
    rating: 4.9,
    reviews: 512,
    brand: "Sony",
    featured: true
  },
  {
    name: "Canon EOS Rebel T7 DSLR Camera",
    price: 479.99,
    originalPrice: 549.99,
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&auto=format&fit=crop",
    description: "Ideal for beginners, this camera bundle comes with 18-55mm lens, built-in Wi-Fi and NFC connectivity, and full HD 1080p video recording.",
    category: "electronics",
    stock: 20,
    rating: 4.6,
    reviews: 184,
    brand: "Canon",
    featured: true
  },
  {
    name: "MacBook Pro 14-inch M2",
    price: 1899.00,
    originalPrice: 1999.00,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop",
    description: "Supercharged by M2 Pro, with a stunning Liquid Retina XDR display, incredible battery life, and all the ports you need.",
    category: "electronics",
    stock: 15,
    rating: 4.9,
    reviews: 420,
    brand: "Apple",
    featured: true
  },
  {
    name: "GoPro HERO11 Black Action Camera",
    price: 349.99,
    originalPrice: 399.99,
    image: "https://images.unsplash.com/photo-1564466809058-bf4114d55352?w=600&auto=format&fit=crop",
    description: "Waterproof action camera with 5.3K60 Ultra HD video, 27MP photos, 1/1.9-inch image sensor, live streaming, and webcam stabilization.",
    category: "electronics",
    stock: 28,
    rating: 4.7,
    reviews: 210,
    brand: "GoPro",
    featured: true
  },
  {
    name: "Classic Crewneck Cotton T-Shirt",
    price: 24.99,
    originalPrice: 35.00,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&auto=format&fit=crop",
    description: "100% premium combed cotton t-shirt. Breathable, durable, and crafted for maximum everyday comfort.",
    category: "clothing",
    stock: 120,
    rating: 4.5,
    reviews: 156,
    brand: "Nike",
    featured: true
  },
  {
    name: "Men's Waterproof Winter Parka",
    price: 139.99,
    originalPrice: 189.99,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop",
    description: "Heavy-duty thermal insulated winter coat with detachable faux fur hood and waterproof shell.",
    category: "clothing",
    stock: 40,
    rating: 4.7,
    reviews: 98,
    brand: "North Face",
    featured: false
  },
  {
    name: "Slim Fit Stretch Denim Jeans",
    price: 49.99,
    originalPrice: 69.99,
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&auto=format&fit=crop",
    description: "Modern slim fit denim jeans with flexible stretch fabric for effortless all-day movement and style.",
    category: "clothing",
    stock: 65,
    rating: 4.6,
    reviews: 142,
    brand: "Levi's",
    featured: true
  },
  {
    name: "Genuine Leather Bifold Wallet",
    price: 38.00,
    originalPrice: 55.00,
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&auto=format&fit=crop",
    description: "Handcrafted full-grain leather wallet equipped with RFID-blocking technology and 8 card slots.",
    category: "accessories",
    stock: 90,
    rating: 4.6,
    reviews: 87,
    brand: "Fossil",
    featured: false
  },
  {
    name: "Ergonomic Aluminum Laptop Stand",
    price: 39.99,
    originalPrice: 59.99,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop",
    description: "Sturdy aluminum riser that promotes better posture and improves laptop heat dissipation.",
    category: "accessories",
    stock: 50,
    rating: 4.5,
    reviews: 130,
    brand: "Logitech",
    featured: false
  },
  {
    name: "Blue Travel Canvas Duffle Bag",
    price: 59.99,
    originalPrice: 85.00,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop",
    description: "Durable water-resistant canvas duffle bag ideal for weekend getaways, gym sessions, and flights.",
    category: "accessories",
    stock: 35,
    rating: 4.7,
    reviews: 64,
    brand: "Herschel",
    featured: false
  },
  {
    name: "Keurig Single-Serve Coffee Maker",
    price: 89.99,
    originalPrice: 119.99,
    image: "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=600&auto=format&fit=crop",
    description: "Brews multiple cup sizes in minutes with a 48 oz removable water reservoir and energy-saving auto off.",
    category: "home",
    stock: 40,
    rating: 4.4,
    reviews: 215,
    brand: "Keurig",
    featured: true
  },
  {
    name: "Stainless Steel Electric Kettle 1.7L",
    price: 34.99,
    originalPrice: 49.99,
    image: "https://images.unsplash.com/photo-1588854337236-6889d631faa8?w=600&auto=format&fit=crop",
    description: "Fast-boil 1500W electric kettle with auto-shutoff, boil-dry protection, and LED indicator light.",
    category: "home",
    stock: 70,
    rating: 4.5,
    reviews: 178,
    brand: "Philips",
    featured: false
  },
  {
    name: "Stand Food Mixer with Dough Hook",
    price: 129.99,
    originalPrice: 179.99,
    image: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=600&auto=format&fit=crop",
    description: "660W 6-speed kitchen stand mixer with 5.5-quart stainless steel bowl, whisk, dough hook, and beater.",
    category: "home",
    stock: 25,
    rating: 4.8,
    reviews: 95,
    brand: "KitchenAid",
    featured: true
  },
  {
    name: "Adidas Ultraboost Light Running Shoes",
    price: 139.99,
    originalPrice: 190.00,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop",
    description: "Next-generation energy-returning running shoes with lightweight BOOST midsole and Continental rubber outsole.",
    category: "sports",
    stock: 55,
    rating: 4.8,
    reviews: 380,
    brand: "Adidas",
    featured: true
  },
  {
    name: "Waterproof Smart Fitness Tracker",
    price: 49.99,
    originalPrice: 69.99,
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&auto=format&fit=crop",
    description: "All-day activity tracker with 24/7 heart rate monitor, sleep tracking, 14 sport modes, and 10-day battery life.",
    category: "sports",
    stock: 80,
    rating: 4.5,
    reviews: 165,
    brand: "Fitbit",
    featured: false
  }
];

module.exports = products;
